language: c
dist: trusty
sudo: required
env:
  - PGDATA=`pwd`/data PGPORT=61958

before_script:
  - ./configure
  - export PATH="$(pwd)"/bin:$PATH
  - export core_count=$(nproc || echo 4) && echo core_count = $core_count

script: make check -j $core_count LC_ALL="C"

after_failure:
  - cat src/test/regress/regression.diffs