language: c
dist: trusty
sudo: required
env:
 - AGDATA=`pwd`/data PGPORT=61958

before_script:
 - ./configure --prefix="$(pwd)"
 - make install > /dev/null
 - export PATH="$(pwd)"/bin:$PATH

script: make check -C src/bin LC_ALL="C"

after_failure:
 - cat src/test/regress/regression.diffs
